### ISSUE TITLE
Occupying too much disk space

### ISSUE THREAD

**Issue by FishWoWater** [parataaito/trellis_api#1]
![image](https://github.com/user-attachments/assets/9b1e6dd1-08c6-4563-b51b-5292df6c2c2e)
![image](https://github.com/user-attachments/assets/4047bec9-fb37-4d39-a65d-bd200a9c8cb5)

I have tried many times, all end up with `no space left on device`,  while I am having 270GB+ space. Intuitively pulling an image and creating a  docker environment should take so much space.

**Comment by parataaito** [comment]
I am not sure I understand where the issue occurs.

Is it when you build the Docker image?
Or is it when you run the container ?

In my case, after building the image, i get a 23 GB image.
![image](https://github.com/user-attachments/assets/a6f9ebcf-b69c-4e6e-b82e-bb13d18c47af)

This is without taking into account the model weights that will be downloaded before the processing.

**Comment by FishWoWater** [comment]
> I am not sure I understand where the issue occurs.
> 
> Is it when you build the Docker image? Or is it when you run the container ?
> 
> In my case, after building the image, i get a 23 GB image. ![image](https://private-user-images.githubusercontent.com/87200263/396508272-a6f9ebcf-b69c-4e6e-b82e-bb13d18c47af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDE1MjMsIm5iZiI6MTczNDQ0MTIyMywicGF0aCI6Ii84NzIwMDI2My8zOTY1MDgyNzItYTZmOWViY2YtYjY5Yy00ZTZlLWI4MmUtYmIxM2QxOGM0N2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDEzMTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNmUzM2UxYzM2ZGE1ZDkxZGEyZjAxMDJkOWQ4NzU3NTZlYmUwMzEzZjc0ZDhiNDg5M2RiN2UwNDY0ZTMyOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WT8tr90Z2k3p4XPnvnDoIk8v9FNnL-gl8l1N1AaOPXQ)
> 
> This is without taking into account the model weights that will be downloaded before the processing.

It happened during building the docker, around step 14/32,  and that's when it writes all of my 250G+ disk and reports "no space left on device". I guess there are too many things cached, so although the final image is 23GB, the build process may require much much more.

**Comment by parataaito** [comment]
I'll check what I can do. Otherwise, I will host the built docker image on my Google Drive.

**Comment by parataaito** [comment]
I updated the README. 

You can now skip the Docker building step and download the pre-built image from Docker Hub: https://hub.docker.com/repository/docker/plenost/trellis-processor/general

**Comment by FishWoWater** [comment]
Could you please build the docker again on your machine and monitor the change of disk usage？In that case, I can know whether it's a problem of my environment. A built docker image will also be very very helpful. Thank you very much : )
发自我的小米在 Parata ito ***@***.***>，2024年12月17日 21:18写道：
I'll check what I can do. Otherwise, I will host the built docker image on my Google Drive.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/parataaito/trellis_api/issues/1#issuecomment-2548440166",
"url": "https://github.com/parataaito/trellis_api/issues/1#issuecomment-2548440166",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by FishWoWater** [comment]
Thank you very much!!!
发自我的小米在 Parata ito ***@***.***>，2024年12月17日 23:24写道：
I updated the README.
You can now skip the Docker building step and download the pre-built image from Docker Hub: https://hub.docker.com/repository/docker/plenost/trellis-processor/general

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/parataaito/trellis_api/issues/1#issuecomment-2548749239",
"url": "https://github.com/parataaito/trellis_api/issues/1#issuecomment-2548749239",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
